module.exports = {
    USER_LOGIN : 1001,
    USER_CREATE : 1000,
    USER_UPDATE :1002,
    USER_SEND_MESSAGE: 2000,

    USER_CALL_VIDEO_ONE_CLIENT : 2200,

    MESSAGE_TYPE_OFF_IMAGE: 'img',
    MESSAGE_TYPE_OFF_TEXT: 'text',
    MESSAGE_TYPE_OFF_AUDIO : 'audio',
    MESSAGE_TYPE_OFF_OTHER : 'other',

    SERVER_SEND_FRIEND_ONLINE:4000,

    SERVER_SEND_HAS_FOLLOW:3000,
    SERVER_SEND_ACCEPT_FOLLOW:3001,

    CLIENT_SENT_NOTIFICATION:4000
};